version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 40
  ignore:
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.13.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.9
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
  - dependency-name: helmet
    versions:
    - 4.3.1
  - dependency-name: supertest
    versions:
    - 6.0.1
  - dependency-name: nodemon
    versions:
    - 2.0.6
